// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BatteryState.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_BATTERYSTATE_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_BATTERYSTATE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated BatteryState is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(BATTERYSTATE_SOURCE)
#define BATTERYSTATE_DllAPI __declspec(dllexport)
#else
#define BATTERYSTATE_DllAPI __declspec(dllimport)
#endif  // BATTERYSTATE_SOURCE
#else
#define BATTERYSTATE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define BATTERYSTATE_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace booster_interface {

namespace msg {

/*!
 * @brief This class represents the structure BatteryState defined by the user
 * in the IDL file.
 * @ingroup BatteryState
 */
class BatteryState : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::BatteryState that
   * will be copied.
   */
  eProsima_user_DllExport BatteryState(const BatteryState& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::BatteryState that
   * will be copied.
   */
  eProsima_user_DllExport BatteryState(BatteryState&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::BatteryState that
   * will be copied.
   */
  eProsima_user_DllExport BatteryState& operator=(const BatteryState& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::BatteryState that
   * will be copied.
   */
  eProsima_user_DllExport BatteryState& operator=(BatteryState&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::BatteryState object to compare.
   */
  eProsima_user_DllExport bool operator==(const BatteryState& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::BatteryState object to compare.
   */
  eProsima_user_DllExport bool operator!=(const BatteryState& x) const;

  /*!
   * @brief This function sets a value in member voltage
   * @param _voltage New value for member voltage
   */
  eProsima_user_DllExport void voltage(float _voltage);

  /*!
   * @brief This function returns the value of member voltage
   * @return Value of member voltage
   */
  eProsima_user_DllExport float voltage() const;

  /*!
   * @brief This function returns a reference to member voltage
   * @return Reference to member voltage
   */
  eProsima_user_DllExport float& voltage();

  /*!
   * @brief This function sets a value in member current
   * @param _current New value for member current
   */
  eProsima_user_DllExport void current(float _current);

  /*!
   * @brief This function returns the value of member current
   * @return Value of member current
   */
  eProsima_user_DllExport float current() const;

  /*!
   * @brief This function returns a reference to member current
   * @return Reference to member current
   */
  eProsima_user_DllExport float& current();

  /*!
   * @brief This function sets a value in member soc
   * @param _soc New value for member soc
   */
  eProsima_user_DllExport void soc(float _soc);

  /*!
   * @brief This function returns the value of member soc
   * @return Value of member soc
   */
  eProsima_user_DllExport float soc() const;

  /*!
   * @brief This function returns a reference to member soc
   * @return Reference to member soc
   */
  eProsima_user_DllExport float& soc();

  /*!
   * @brief This function sets a value in member average_voltage
   * @param _average_voltage New value for member average_voltage
   */
  eProsima_user_DllExport void average_voltage(float _average_voltage);

  /*!
   * @brief This function returns the value of member average_voltage
   * @return Value of member average_voltage
   */
  eProsima_user_DllExport float average_voltage() const;

  /*!
   * @brief This function returns a reference to member average_voltage
   * @return Reference to member average_voltage
   */
  eProsima_user_DllExport float& average_voltage();

 private:
  float m_voltage{0.0};
  float m_current{0.0};
  float m_soc{0.0};
  float m_average_voltage{0.0};

 public:
  typedef BatteryState type;

  eProsima_user_DllExport BatteryState();

  eProsima_user_DllExport ~BatteryState() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace msg

}  // namespace booster_interface

#endif  // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_BATTERYSTATE_H_
