// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HandTouchParam.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_HANDTOUCHPARAM_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_HANDTOUCHPARAM_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated HandTouchParam is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(HANDTOUCHPARAM_SOURCE)
#define HANDTOUCHPARAM_DllAPI __declspec(dllexport)
#else
#define HANDTOUCHPARAM_DllAPI __declspec(dllimport)
#endif  // HANDTOUCHPARAM_SOURCE
#else
#define HANDTOUCHPARAM_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define HANDTOUCHPARAM_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace booster_interface {

namespace msg {

/*!
 * @brief This class represents the structure HandTouchParam defined by the user
 * in the IDL file.
 * @ingroup HandTouchParam
 */
class HandTouchParam : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::HandTouchParam
   * that will be copied.
   */
  eProsima_user_DllExport HandTouchParam(const HandTouchParam& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::HandTouchParam
   * that will be copied.
   */
  eProsima_user_DllExport HandTouchParam(HandTouchParam&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::HandTouchParam
   * that will be copied.
   */
  eProsima_user_DllExport HandTouchParam& operator=(const HandTouchParam& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::HandTouchParam
   * that will be copied.
   */
  eProsima_user_DllExport HandTouchParam& operator=(
      HandTouchParam&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::HandTouchParam object to compare.
   */
  eProsima_user_DllExport bool operator==(const HandTouchParam& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::HandTouchParam object to compare.
   */
  eProsima_user_DllExport bool operator!=(const HandTouchParam& x) const;

  /*!
   * @brief This function copies the value in member finger_one
   * @param _finger_one New value to be copied in member finger_one
   */
  eProsima_user_DllExport void finger_one(
      const std::vector<uint8_t>& _finger_one);

  /*!
   * @brief This function moves the value in member finger_one
   * @param _finger_one New value to be moved in member finger_one
   */
  eProsima_user_DllExport void finger_one(std::vector<uint8_t>&& _finger_one);

  /*!
   * @brief This function returns a constant reference to member finger_one
   * @return Constant reference to member finger_one
   */
  eProsima_user_DllExport const std::vector<uint8_t>& finger_one() const;

  /*!
   * @brief This function returns a reference to member finger_one
   * @return Reference to member finger_one
   */
  eProsima_user_DllExport std::vector<uint8_t>& finger_one();

  /*!
   * @brief This function copies the value in member finger_two
   * @param _finger_two New value to be copied in member finger_two
   */
  eProsima_user_DllExport void finger_two(
      const std::vector<uint8_t>& _finger_two);

  /*!
   * @brief This function moves the value in member finger_two
   * @param _finger_two New value to be moved in member finger_two
   */
  eProsima_user_DllExport void finger_two(std::vector<uint8_t>&& _finger_two);

  /*!
   * @brief This function returns a constant reference to member finger_two
   * @return Constant reference to member finger_two
   */
  eProsima_user_DllExport const std::vector<uint8_t>& finger_two() const;

  /*!
   * @brief This function returns a reference to member finger_two
   * @return Reference to member finger_two
   */
  eProsima_user_DllExport std::vector<uint8_t>& finger_two();

  /*!
   * @brief This function copies the value in member finger_three
   * @param _finger_three New value to be copied in member finger_three
   */
  eProsima_user_DllExport void finger_three(
      const std::vector<uint8_t>& _finger_three);

  /*!
   * @brief This function moves the value in member finger_three
   * @param _finger_three New value to be moved in member finger_three
   */
  eProsima_user_DllExport void finger_three(
      std::vector<uint8_t>&& _finger_three);

  /*!
   * @brief This function returns a constant reference to member finger_three
   * @return Constant reference to member finger_three
   */
  eProsima_user_DllExport const std::vector<uint8_t>& finger_three() const;

  /*!
   * @brief This function returns a reference to member finger_three
   * @return Reference to member finger_three
   */
  eProsima_user_DllExport std::vector<uint8_t>& finger_three();

  /*!
   * @brief This function copies the value in member finger_four
   * @param _finger_four New value to be copied in member finger_four
   */
  eProsima_user_DllExport void finger_four(
      const std::vector<uint8_t>& _finger_four);

  /*!
   * @brief This function moves the value in member finger_four
   * @param _finger_four New value to be moved in member finger_four
   */
  eProsima_user_DllExport void finger_four(std::vector<uint8_t>&& _finger_four);

  /*!
   * @brief This function returns a constant reference to member finger_four
   * @return Constant reference to member finger_four
   */
  eProsima_user_DllExport const std::vector<uint8_t>& finger_four() const;

  /*!
   * @brief This function returns a reference to member finger_four
   * @return Reference to member finger_four
   */
  eProsima_user_DllExport std::vector<uint8_t>& finger_four();

  /*!
   * @brief This function copies the value in member finger_five
   * @param _finger_five New value to be copied in member finger_five
   */
  eProsima_user_DllExport void finger_five(
      const std::vector<uint8_t>& _finger_five);

  /*!
   * @brief This function moves the value in member finger_five
   * @param _finger_five New value to be moved in member finger_five
   */
  eProsima_user_DllExport void finger_five(std::vector<uint8_t>&& _finger_five);

  /*!
   * @brief This function returns a constant reference to member finger_five
   * @return Constant reference to member finger_five
   */
  eProsima_user_DllExport const std::vector<uint8_t>& finger_five() const;

  /*!
   * @brief This function returns a reference to member finger_five
   * @return Reference to member finger_five
   */
  eProsima_user_DllExport std::vector<uint8_t>& finger_five();

  /*!
   * @brief This function copies the value in member finger_palm
   * @param _finger_palm New value to be copied in member finger_palm
   */
  eProsima_user_DllExport void finger_palm(
      const std::vector<uint8_t>& _finger_palm);

  /*!
   * @brief This function moves the value in member finger_palm
   * @param _finger_palm New value to be moved in member finger_palm
   */
  eProsima_user_DllExport void finger_palm(std::vector<uint8_t>&& _finger_palm);

  /*!
   * @brief This function returns a constant reference to member finger_palm
   * @return Constant reference to member finger_palm
   */
  eProsima_user_DllExport const std::vector<uint8_t>& finger_palm() const;

  /*!
   * @brief This function returns a reference to member finger_palm
   * @return Reference to member finger_palm
   */
  eProsima_user_DllExport std::vector<uint8_t>& finger_palm();

 private:
  std::vector<uint8_t> m_finger_one;
  std::vector<uint8_t> m_finger_two;
  std::vector<uint8_t> m_finger_three;
  std::vector<uint8_t> m_finger_four;
  std::vector<uint8_t> m_finger_five;
  std::vector<uint8_t> m_finger_palm;

 public:
  typedef HandTouchParam type;

  eProsima_user_DllExport HandTouchParam();

  eProsima_user_DllExport ~HandTouchParam() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace msg

}  // namespace booster_interface

#endif  // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_HANDTOUCHPARAM_H_
