// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RobotStates.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_ROBOTSTATES_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_ROBOTSTATES_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#include "RobotStates.h"

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated RobotStates is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ROBOTSTATES_SOURCE)
#define ROBOTSTATES_DllAPI __declspec(dllexport)
#else
#define ROBOTSTATES_DllAPI __declspec(dllimport)
#endif  // ROBOTSTATES_SOURCE
#else
#define ROBOTSTATES_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ROBOTSTATES_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace booster_interface {

namespace msg {

/*!
 * @brief This class represents the structure RobotStatesMsg defined by the user
 * in the IDL file.
 * @ingroup RobotStates
 */
class RobotStatesMsg : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::RobotStatesMsg
   * that will be copied.
   */
  eProsima_user_DllExport RobotStatesMsg(const RobotStatesMsg& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::RobotStatesMsg
   * that will be copied.
   */
  eProsima_user_DllExport RobotStatesMsg(RobotStatesMsg&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::RobotStatesMsg
   * that will be copied.
   */
  eProsima_user_DllExport RobotStatesMsg& operator=(const RobotStatesMsg& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::RobotStatesMsg
   * that will be copied.
   */
  eProsima_user_DllExport RobotStatesMsg& operator=(
      RobotStatesMsg&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::RobotStatesMsg object to compare.
   */
  eProsima_user_DllExport bool operator==(const RobotStatesMsg& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::RobotStatesMsg object to compare.
   */
  eProsima_user_DllExport bool operator!=(const RobotStatesMsg& x) const;

  /*!
   * @brief This function sets a value in member current_mode
   * @param _current_mode New value for member current_mode
   */
  eProsima_user_DllExport void current_mode(int32_t _current_mode);

  /*!
   * @brief This function returns the value of member current_mode
   * @return Value of member current_mode
   */
  eProsima_user_DllExport int32_t current_mode() const;

  /*!
   * @brief This function returns a reference to member current_mode
   * @return Reference to member current_mode
   */
  eProsima_user_DllExport int32_t& current_mode();

  /*!
   * @brief This function sets a value in member current_body_control
   * @param _current_body_control New value for member current_body_control
   */
  eProsima_user_DllExport void current_body_control(
      int32_t _current_body_control);

  /*!
   * @brief This function returns the value of member current_body_control
   * @return Value of member current_body_control
   */
  eProsima_user_DllExport int32_t current_body_control() const;

  /*!
   * @brief This function returns a reference to member current_body_control
   * @return Reference to member current_body_control
   */
  eProsima_user_DllExport int32_t& current_body_control();

  /*!
   * @brief This function copies the value in member current_actions
   * @param _current_actions New value to be copied in member current_actions
   */
  eProsima_user_DllExport void current_actions(
      const std::vector<int32_t>& _current_actions);

  /*!
   * @brief This function moves the value in member current_actions
   * @param _current_actions New value to be moved in member current_actions
   */
  eProsima_user_DllExport void current_actions(
      std::vector<int32_t>&& _current_actions);

  /*!
   * @brief This function returns a constant reference to member current_actions
   * @return Constant reference to member current_actions
   */
  eProsima_user_DllExport const std::vector<int32_t>& current_actions() const;

  /*!
   * @brief This function returns a reference to member current_actions
   * @return Reference to member current_actions
   */
  eProsima_user_DllExport std::vector<int32_t>& current_actions();

 private:
  int32_t m_current_mode{0};
  int32_t m_current_body_control{0};
  std::vector<int32_t> m_current_actions;

 public:
  typedef RobotStatesMsg type;

  eProsima_user_DllExport RobotStatesMsg();

  eProsima_user_DllExport ~RobotStatesMsg() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace msg

}  // namespace booster_interface

#endif  // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_ROBOTSTATES_H_
