// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Subtitle.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_SUBTITLE_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_SUBTITLE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated Subtitle is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(SUBTITLE_SOURCE)
#define SUBTITLE_DllAPI __declspec(dllexport)
#else
#define SUBTITLE_DllAPI __declspec(dllimport)
#endif  // SUBTITLE_SOURCE
#else
#define SUBTITLE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define SUBTITLE_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace booster_interface {

namespace msg {

/*!
 * @brief This class represents the structure Subtitle defined by the user in
 * the IDL file.
 * @ingroup Subtitle
 */
class Subtitle : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::Subtitle that will
   * be copied.
   */
  eProsima_user_DllExport Subtitle(const Subtitle& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::Subtitle that will
   * be copied.
   */
  eProsima_user_DllExport Subtitle(Subtitle&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::Subtitle that will
   * be copied.
   */
  eProsima_user_DllExport Subtitle& operator=(const Subtitle& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::Subtitle that will
   * be copied.
   */
  eProsima_user_DllExport Subtitle& operator=(Subtitle&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Subtitle object to compare.
   */
  eProsima_user_DllExport bool operator==(const Subtitle& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Subtitle object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Subtitle& x) const;

  /*!
   * @brief This function copies the value in member magic_number
   * @param _magic_number New value to be copied in member magic_number
   */
  eProsima_user_DllExport void magic_number(const std::string& _magic_number);

  /*!
   * @brief This function moves the value in member magic_number
   * @param _magic_number New value to be moved in member magic_number
   */
  eProsima_user_DllExport void magic_number(std::string&& _magic_number);

  /*!
   * @brief This function returns a constant reference to member magic_number
   * @return Constant reference to member magic_number
   */
  eProsima_user_DllExport const std::string& magic_number() const;

  /*!
   * @brief This function returns a reference to member magic_number
   * @return Reference to member magic_number
   */
  eProsima_user_DllExport std::string& magic_number();

  /*!
   * @brief This function copies the value in member text
   * @param _text New value to be copied in member text
   */
  eProsima_user_DllExport void text(const std::string& _text);

  /*!
   * @brief This function moves the value in member text
   * @param _text New value to be moved in member text
   */
  eProsima_user_DllExport void text(std::string&& _text);

  /*!
   * @brief This function returns a constant reference to member text
   * @return Constant reference to member text
   */
  eProsima_user_DllExport const std::string& text() const;

  /*!
   * @brief This function returns a reference to member text
   * @return Reference to member text
   */
  eProsima_user_DllExport std::string& text();

  /*!
   * @brief This function copies the value in member language
   * @param _language New value to be copied in member language
   */
  eProsima_user_DllExport void language(const std::string& _language);

  /*!
   * @brief This function moves the value in member language
   * @param _language New value to be moved in member language
   */
  eProsima_user_DllExport void language(std::string&& _language);

  /*!
   * @brief This function returns a constant reference to member language
   * @return Constant reference to member language
   */
  eProsima_user_DllExport const std::string& language() const;

  /*!
   * @brief This function returns a reference to member language
   * @return Reference to member language
   */
  eProsima_user_DllExport std::string& language();

  /*!
   * @brief This function copies the value in member user_id
   * @param _user_id New value to be copied in member user_id
   */
  eProsima_user_DllExport void user_id(const std::string& _user_id);

  /*!
   * @brief This function moves the value in member user_id
   * @param _user_id New value to be moved in member user_id
   */
  eProsima_user_DllExport void user_id(std::string&& _user_id);

  /*!
   * @brief This function returns a constant reference to member user_id
   * @return Constant reference to member user_id
   */
  eProsima_user_DllExport const std::string& user_id() const;

  /*!
   * @brief This function returns a reference to member user_id
   * @return Reference to member user_id
   */
  eProsima_user_DllExport std::string& user_id();

  /*!
   * @brief This function sets a value in member seq
   * @param _seq New value for member seq
   */
  eProsima_user_DllExport void seq(int32_t _seq);

  /*!
   * @brief This function returns the value of member seq
   * @return Value of member seq
   */
  eProsima_user_DllExport int32_t seq() const;

  /*!
   * @brief This function returns a reference to member seq
   * @return Reference to member seq
   */
  eProsima_user_DllExport int32_t& seq();

  /*!
   * @brief This function sets a value in member definite
   * @param _definite New value for member definite
   */
  eProsima_user_DllExport void definite(bool _definite);

  /*!
   * @brief This function returns the value of member definite
   * @return Value of member definite
   */
  eProsima_user_DllExport bool definite() const;

  /*!
   * @brief This function returns a reference to member definite
   * @return Reference to member definite
   */
  eProsima_user_DllExport bool& definite();

  /*!
   * @brief This function sets a value in member paragraph
   * @param _paragraph New value for member paragraph
   */
  eProsima_user_DllExport void paragraph(bool _paragraph);

  /*!
   * @brief This function returns the value of member paragraph
   * @return Value of member paragraph
   */
  eProsima_user_DllExport bool paragraph() const;

  /*!
   * @brief This function returns a reference to member paragraph
   * @return Reference to member paragraph
   */
  eProsima_user_DllExport bool& paragraph();

  /*!
   * @brief This function sets a value in member round_id
   * @param _round_id New value for member round_id
   */
  eProsima_user_DllExport void round_id(int32_t _round_id);

  /*!
   * @brief This function returns the value of member round_id
   * @return Value of member round_id
   */
  eProsima_user_DllExport int32_t round_id() const;

  /*!
   * @brief This function returns a reference to member round_id
   * @return Reference to member round_id
   */
  eProsima_user_DllExport int32_t& round_id();

 private:
  std::string m_magic_number;
  std::string m_text;
  std::string m_language;
  std::string m_user_id;
  int32_t m_seq{0};
  bool m_definite{false};
  bool m_paragraph{false};
  int32_t m_round_id{0};

 public:
  typedef Subtitle type;

  eProsima_user_DllExport Subtitle();

  eProsima_user_DllExport ~Subtitle() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace msg

}  // namespace booster_interface

#endif  // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_SUBTITLE_H_
